### ISSUE TITLE
cnnot work

### ISSUE THREAD

**Issue by Geapefurit** [reservoirprotocol/reservoir-sync-node#70]
cnnot work for me
![1692861682603](https://github.com/reservoirprotocol/reservoir-sync-node/assets/25075249/e22ee889-1ba9-446d-bea6-b66707532602)

**Comment by opensourceinterfaces292** [comment]
Hello @Geapefurit ! 🙂

I had the issue.

For me the cause what that I was trying to run the Sync Node on the `Mainnet` and my account was on the free plan.

When looking at the Websockets page in the Reservoir Tools documentation, we see that that the `Mainnet` websockets are only available on the Startup plan.

Hope this helps!

**Comment by Geapefurit** [comment]
Thank U！
I kown.Did you run on the plan except free？

**Comment by opensourceinterfaces292** [comment]
I only ran the Sync Node on the `Goerli` testnet as of now.
